/* tslint:disable */
/* eslint-disable */
/**
 * POIZON Market API
 * API документация для маркетплейса POIZON
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateProductDto } from '../models';
// @ts-ignore
import type { PaginatedResponseDto } from '../models';
// @ts-ignore
import type { ProductBasicDto } from '../models';
// @ts-ignore
import type { ProductVariantDto } from '../models';
// @ts-ignore
import type { ProductVariantsResponseDto } from '../models';
/**
 * ProductsApi - axios parameter creator
 * @export
 */
export const ProductsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Добавить вариант товара
         * @param {string} id ID товара
         * @param {ProductVariantDto} productVariantDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addProductVariant: async (id: string, productVariantDto: ProductVariantDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('addProductVariant', 'id', id)
            // verify required parameter 'productVariantDto' is not null or undefined
            assertParamExists('addProductVariant', 'productVariantDto', productVariantDto)
            const localVarPath = `/products/{id}/variants`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(productVariantDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Создать новый товар
         * @param {CreateProductDto} createProductDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProduct: async (createProductDto: CreateProductDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createProductDto' is not null or undefined
            assertParamExists('createProduct', 'createProductDto', createProductDto)
            const localVarPath = `/products`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createProductDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get product by slug
         * @param {string} categorySlug 
         * @param {string} brandSlug 
         * @param {string} productSlug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findBySlug: async (categorySlug: string, brandSlug: string, productSlug: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'categorySlug' is not null or undefined
            assertParamExists('findBySlug', 'categorySlug', categorySlug)
            // verify required parameter 'brandSlug' is not null or undefined
            assertParamExists('findBySlug', 'brandSlug', brandSlug)
            // verify required parameter 'productSlug' is not null or undefined
            assertParamExists('findBySlug', 'productSlug', productSlug)
            const localVarPath = `/products/slug/{categorySlug}/{brandSlug}/{productSlug}`
                .replace(`{${"categorySlug"}}`, encodeURIComponent(String(categorySlug)))
                .replace(`{${"brandSlug"}}`, encodeURIComponent(String(brandSlug)))
                .replace(`{${"productSlug"}}`, encodeURIComponent(String(productSlug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Получить все товары с пагинацией
         * @param {number} [page] Номер страницы
         * @param {number} [limit] Количество элементов на странице
         * @param {string} [categoryId] ID категории для фильтрации
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllProducts: async (page?: number, limit?: number, categoryId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/products`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (categoryId !== undefined) {
                localVarQueryParameter['categoryId'] = categoryId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Получить базовую информацию о товаре
         * @param {string} id ID товара
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProductById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getProductById', 'id', id)
            const localVarPath = `/products/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Получить варианты товара
         * @param {string} id ID товара
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProductVariants: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getProductVariants', 'id', id)
            const localVarPath = `/products/{id}/variants`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProductsApi - functional programming interface
 * @export
 */
export const ProductsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProductsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Добавить вариант товара
         * @param {string} id ID товара
         * @param {ProductVariantDto} productVariantDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addProductVariant(id: string, productVariantDto: ProductVariantDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProductVariantDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addProductVariant(id, productVariantDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductsApi.addProductVariant']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Создать новый товар
         * @param {CreateProductDto} createProductDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createProduct(createProductDto: CreateProductDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProductBasicDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createProduct(createProductDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductsApi.createProduct']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get product by slug
         * @param {string} categorySlug 
         * @param {string} brandSlug 
         * @param {string} productSlug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findBySlug(categorySlug: string, brandSlug: string, productSlug: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findBySlug(categorySlug, brandSlug, productSlug, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductsApi.findBySlug']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Получить все товары с пагинацией
         * @param {number} [page] Номер страницы
         * @param {number} [limit] Количество элементов на странице
         * @param {string} [categoryId] ID категории для фильтрации
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllProducts(page?: number, limit?: number, categoryId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllProducts(page, limit, categoryId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductsApi.getAllProducts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Получить базовую информацию о товаре
         * @param {string} id ID товара
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProductById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProductBasicDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProductById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductsApi.getProductById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Получить варианты товара
         * @param {string} id ID товара
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProductVariants(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProductVariantsResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProductVariants(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductsApi.getProductVariants']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProductsApi - factory interface
 * @export
 */
export const ProductsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProductsApiFp(configuration)
    return {
        /**
         * 
         * @summary Добавить вариант товара
         * @param {string} id ID товара
         * @param {ProductVariantDto} productVariantDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addProductVariant(id: string, productVariantDto: ProductVariantDto, options?: RawAxiosRequestConfig): AxiosPromise<ProductVariantDto> {
            return localVarFp.addProductVariant(id, productVariantDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Создать новый товар
         * @param {CreateProductDto} createProductDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProduct(createProductDto: CreateProductDto, options?: RawAxiosRequestConfig): AxiosPromise<ProductBasicDto> {
            return localVarFp.createProduct(createProductDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get product by slug
         * @param {string} categorySlug 
         * @param {string} brandSlug 
         * @param {string} productSlug 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findBySlug(categorySlug: string, brandSlug: string, productSlug: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.findBySlug(categorySlug, brandSlug, productSlug, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Получить все товары с пагинацией
         * @param {number} [page] Номер страницы
         * @param {number} [limit] Количество элементов на странице
         * @param {string} [categoryId] ID категории для фильтрации
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllProducts(page?: number, limit?: number, categoryId?: string, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedResponseDto> {
            return localVarFp.getAllProducts(page, limit, categoryId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Получить базовую информацию о товаре
         * @param {string} id ID товара
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProductById(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ProductBasicDto> {
            return localVarFp.getProductById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Получить варианты товара
         * @param {string} id ID товара
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProductVariants(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ProductVariantsResponseDto> {
            return localVarFp.getProductVariants(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProductsApi - object-oriented interface
 * @export
 * @class ProductsApi
 * @extends {BaseAPI}
 */
export class ProductsApi extends BaseAPI {
    /**
     * 
     * @summary Добавить вариант товара
     * @param {string} id ID товара
     * @param {ProductVariantDto} productVariantDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApi
     */
    public addProductVariant(id: string, productVariantDto: ProductVariantDto, options?: RawAxiosRequestConfig) {
        return ProductsApiFp(this.configuration).addProductVariant(id, productVariantDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Создать новый товар
     * @param {CreateProductDto} createProductDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApi
     */
    public createProduct(createProductDto: CreateProductDto, options?: RawAxiosRequestConfig) {
        return ProductsApiFp(this.configuration).createProduct(createProductDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get product by slug
     * @param {string} categorySlug 
     * @param {string} brandSlug 
     * @param {string} productSlug 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApi
     */
    public findBySlug(categorySlug: string, brandSlug: string, productSlug: string, options?: RawAxiosRequestConfig) {
        return ProductsApiFp(this.configuration).findBySlug(categorySlug, brandSlug, productSlug, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Получить все товары с пагинацией
     * @param {number} [page] Номер страницы
     * @param {number} [limit] Количество элементов на странице
     * @param {string} [categoryId] ID категории для фильтрации
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApi
     */
    public getAllProducts(page?: number, limit?: number, categoryId?: string, options?: RawAxiosRequestConfig) {
        return ProductsApiFp(this.configuration).getAllProducts(page, limit, categoryId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Получить базовую информацию о товаре
     * @param {string} id ID товара
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApi
     */
    public getProductById(id: string, options?: RawAxiosRequestConfig) {
        return ProductsApiFp(this.configuration).getProductById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Получить варианты товара
     * @param {string} id ID товара
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApi
     */
    public getProductVariants(id: string, options?: RawAxiosRequestConfig) {
        return ProductsApiFp(this.configuration).getProductVariants(id, options).then((request) => request(this.axios, this.basePath));
    }
}

