/* tslint:disable */
/* eslint-disable */
/**
 * POIZON Market API
 * API документация для маркетплейса POIZON
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApproveImportDto
 */
export interface ApproveImportDto {
    /**
     * ID продукта
     * @type {string}
     * @memberof ApproveImportDto
     */
    'productId'?: string;
    /**
     * ID варианта продукта
     * @type {string}
     * @memberof ApproveImportDto
     */
    'variantId'?: string;
}

