/* tslint:disable */
/* eslint-disable */
/**
 * POIZON Market API
 * API документация для маркетплейса POIZON
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthResponseDto
 */
export interface AuthResponseDto {
    /**
     * JWT токен доступа
     * @type {string}
     * @memberof AuthResponseDto
     */
    'accessToken': string;
    /**
     * JWT токен для обновления
     * @type {string}
     * @memberof AuthResponseDto
     */
    'refreshToken': string;
}

