/* tslint:disable */
/* eslint-disable */
/**
 * Poizon Market Recommendation System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RecommendationType } from './recommendation-type';

/**
 * 
 * @export
 * @interface BatchRecommendationRequest
 */
export interface BatchRecommendationRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof BatchRecommendationRequest
     */
    'user_ids': Array<string>;
    /**
     * 
     * @type {number}
     * @memberof BatchRecommendationRequest
     */
    'limit'?: number;
    /**
     * 
     * @type {string}
     * @memberof BatchRecommendationRequest
     */
    'category'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BatchRecommendationRequest
     */
    'brand'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BatchRecommendationRequest
     */
    'min_price'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BatchRecommendationRequest
     */
    'max_price'?: number | null;
    /**
     * 
     * @type {RecommendationType}
     * @memberof BatchRecommendationRequest
     */
    'recommendation_type'?: RecommendationType;
}



