/* tslint:disable */
/* eslint-disable */
/**
 * POIZON Market API
 * API документация для маркетплейса POIZON
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BrandDto
 */
export interface BrandDto {
    /**
     * 
     * @type {string}
     * @memberof BrandDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof BrandDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof BrandDto
     */
    'slug': string;
    /**
     * 
     * @type {string}
     * @memberof BrandDto
     */
    'logoUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof BrandDto
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof BrandDto
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof BrandDto
     */
    'updatedAt': string;
}

