/* tslint:disable */
/* eslint-disable */
/**
 * POIZON Market API
 * API документация для маркетплейса POIZON
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BrandDto } from './brand-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { CategoryDto } from './category-dto';

/**
 * 
 * @export
 * @interface CreateProductDto
 */
export interface CreateProductDto {
    /**
     * Название товара
     * @type {string}
     * @memberof CreateProductDto
     */
    'name': string;
    /**
     * Бренд товара
     * @type {BrandDto}
     * @memberof CreateProductDto
     */
    'brand': BrandDto;
    /**
     * Категория товара
     * @type {CategoryDto}
     * @memberof CreateProductDto
     */
    'category': CategoryDto;
    /**
     * Описание товара
     * @type {string}
     * @memberof CreateProductDto
     */
    'description'?: string;
    /**
     * Медиафайлы товара (изображения, видео)
     * @type {object}
     * @memberof CreateProductDto
     */
    'media': object;
}

