/* tslint:disable */
/* eslint-disable */
/**
 * POIZON Market API
 * API документация для маркетплейса POIZON
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateBrandDto
 */
export interface CreateBrandDto {
    /**
     * The name of the brand
     * @type {string}
     * @memberof CreateBrandDto
     */
    'name': string;
    /**
     * The brand description
     * @type {string}
     * @memberof CreateBrandDto
     */
    'description': string;
    /**
     * URL to the brand logo
     * @type {string}
     * @memberof CreateBrandDto
     */
    'logoUrl'?: string;
}

