/* tslint:disable */
/* eslint-disable */
/**
 * POIZON Market API
 * API документация для маркетплейса POIZON
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateUserContentDto
 */
export interface CreateUserContentDto {
    /**
     * ID продукта
     * @type {string}
     * @memberof CreateUserContentDto
     */
    'productId': string;
    /**
     * Тип контента
     * @type {string}
     * @memberof CreateUserContentDto
     */
    'type': CreateUserContentDtoTypeEnum;
    /**
     * URL контента
     * @type {string}
     * @memberof CreateUserContentDto
     */
    'url': string;
    /**
     * Подпись к контенту
     * @type {string}
     * @memberof CreateUserContentDto
     */
    'caption'?: string;
}

export const CreateUserContentDtoTypeEnum = {
    Video: 'VIDEO',
    Photo: 'PHOTO',
    Link: 'LINK'
} as const;

export type CreateUserContentDtoTypeEnum = typeof CreateUserContentDtoTypeEnum[keyof typeof CreateUserContentDtoTypeEnum];


