/* tslint:disable */
/* eslint-disable */
/**
 * POIZON Market API
 * API документация для маркетплейса POIZON
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ImportedProductDraftDto
 */
export interface ImportedProductDraftDto {
    /**
     * ID черновика
     * @type {string}
     * @memberof ImportedProductDraftDto
     */
    'id': string;
    /**
     * ID продукта на POIZON
     * @type {string}
     * @memberof ImportedProductDraftDto
     */
    'poizonId': string;
    /**
     * Название продукта
     * @type {string}
     * @memberof ImportedProductDraftDto
     */
    'name': string;
    /**
     * Бренд
     * @type {string}
     * @memberof ImportedProductDraftDto
     */
    'brand': string;
    /**
     * Категория
     * @type {string}
     * @memberof ImportedProductDraftDto
     */
    'category': string;
    /**
     * Размер
     * @type {string}
     * @memberof ImportedProductDraftDto
     */
    'size': string;
    /**
     * Цвет
     * @type {string}
     * @memberof ImportedProductDraftDto
     */
    'color': string;
    /**
     * Артикул
     * @type {string}
     * @memberof ImportedProductDraftDto
     */
    'sku': string;
    /**
     * Цена в CNY
     * @type {number}
     * @memberof ImportedProductDraftDto
     */
    'priceCny': number;
    /**
     * URL изображений
     * @type {Array<string>}
     * @memberof ImportedProductDraftDto
     */
    'imageUrls': Array<string>;
    /**
     * Сырые данные
     * @type {object}
     * @memberof ImportedProductDraftDto
     */
    'rawData': object;
    /**
     * Статус обработки
     * @type {string}
     * @memberof ImportedProductDraftDto
     */
    'status': string;
    /**
     * Дата импорта
     * @type {string}
     * @memberof ImportedProductDraftDto
     */
    'importedAt': string;
}

