/* tslint:disable */
/* eslint-disable */
/**
 * POIZON Market API
 * API документация для маркетплейса POIZON
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OrderDto
 */
export interface OrderDto {
    /**
     * ID заказа
     * @type {string}
     * @memberof OrderDto
     */
    'id': string;
    /**
     * ID пользователя
     * @type {string}
     * @memberof OrderDto
     */
    'userId': string;
    /**
     * Статус заказа
     * @type {string}
     * @memberof OrderDto
     */
    'status': string;
    /**
     * Общая стоимость в CNY
     * @type {number}
     * @memberof OrderDto
     */
    'totalPriceCny': number;
    /**
     * Адрес доставки
     * @type {string}
     * @memberof OrderDto
     */
    'deliveryAddress': string;
    /**
     * Телефон
     * @type {string}
     * @memberof OrderDto
     */
    'phone': string;
    /**
     * Дата создания
     * @type {string}
     * @memberof OrderDto
     */
    'createdAt': string;
    /**
     * Дата обновления
     * @type {string}
     * @memberof OrderDto
     */
    'updatedAt': string;
    /**
     * Элементы заказа
     * @type {Array<object>}
     * @memberof OrderDto
     */
    'items': Array<object>;
}

