/* tslint:disable */
/* eslint-disable */
/**
 * POIZON Market API
 * API документация для маркетплейса POIZON
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BrandDto } from './brand-dto';

/**
 * 
 * @export
 * @interface ProductDto
 */
export interface ProductDto {
    /**
     * ID продукта
     * @type {string}
     * @memberof ProductDto
     */
    'id': string;
    /**
     * Название продукта
     * @type {string}
     * @memberof ProductDto
     */
    'name': string;
    /**
     * Медиа данные
     * @type {object}
     * @memberof ProductDto
     */
    'media': object;
    /**
     * ID категории
     * @type {string}
     * @memberof ProductDto
     */
    'categoryId': string;
    /**
     * ID бренда
     * @type {string}
     * @memberof ProductDto
     */
    'brandId': string;
    /**
     * Дата создания
     * @type {string}
     * @memberof ProductDto
     */
    'createdAt': string;
    /**
     * Дата обновления
     * @type {string}
     * @memberof ProductDto
     */
    'updatedAt': string;
    /**
     * Бренд
     * @type {BrandDto}
     * @memberof ProductDto
     */
    'brand': BrandDto;
}

