/* tslint:disable */
/* eslint-disable */
/**
 * Poizon Market Recommendation System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProductMetricsUpdate
 */
export interface ProductMetricsUpdate {
    /**
     * 
     * @type {number}
     * @memberof ProductMetricsUpdate
     */
    'views'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductMetricsUpdate
     */
    'cart_adds'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductMetricsUpdate
     */
    'purchases'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductMetricsUpdate
     */
    'favorites'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductMetricsUpdate
     */
    'clicks'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductMetricsUpdate
     */
    'impressions'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductMetricsUpdate
     */
    'shares'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductMetricsUpdate
     */
    'reviews'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductMetricsUpdate
     */
    'average_rating'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductMetricsUpdate
     */
    'relevance_score'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductMetricsUpdate
     */
    'trending_score'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductMetricsUpdate
     */
    'popularity_score'?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof ProductMetricsUpdate
     */
    'feature_vector'?: Array<number> | null;
    /**
     * 
     * @type {object}
     * @memberof ProductMetricsUpdate
     */
    'metadata'?: object | null;
}

