/* tslint:disable */
/* eslint-disable */
/**
 * Poizon Market Recommendation System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProductVariant } from './product-variant';

/**
 * 
 * @export
 * @interface ProductResponse
 */
export interface ProductResponse {
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    'slug'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    'category_id': string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    'brand_id': string;
    /**
     * 
     * @type {object}
     * @memberof ProductResponse
     */
    'brandData'?: object | null;
    /**
     * 
     * @type {object}
     * @memberof ProductResponse
     */
    'categoryData'?: object | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProductResponse
     */
    'media'?: Array<string>;
    /**
     * 
     * @type {Array<ProductVariant>}
     * @memberof ProductResponse
     */
    'variants'?: Array<ProductVariant>;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponse
     */
    'updated_at': string;
    /**
     * 
     * @type {number}
     * @memberof ProductResponse
     */
    'popularity_score'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProductResponse
     */
    'trending_score'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProductResponse
     */
    'similarity_score'?: number | null;
}

