/* tslint:disable */
/* eslint-disable */
/**
 * POIZON Market API
 * API документация для маркетплейса POIZON
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProductVariantDto } from './product-variant-dto';

/**
 * 
 * @export
 * @interface ProductResponseDto
 */
export interface ProductResponseDto {
    /**
     * ID товара
     * @type {string}
     * @memberof ProductResponseDto
     */
    'id': string;
    /**
     * Название товара
     * @type {string}
     * @memberof ProductResponseDto
     */
    'name': string;
    /**
     * Описание товара
     * @type {string}
     * @memberof ProductResponseDto
     */
    'description': string;
    /**
     * Цена товара
     * @type {number}
     * @memberof ProductResponseDto
     */
    'price': number;
    /**
     * Изображения товара
     * @type {Array<string>}
     * @memberof ProductResponseDto
     */
    'images': Array<string>;
    /**
     * Категория товара
     * @type {string}
     * @memberof ProductResponseDto
     */
    'category': string;
    /**
     * Бренд товара
     * @type {string}
     * @memberof ProductResponseDto
     */
    'brand': string;
    /**
     * Варианты товара
     * @type {Array<ProductVariantDto>}
     * @memberof ProductResponseDto
     */
    'variants'?: Array<ProductVariantDto>;
    /**
     * Рейтинг товара
     * @type {number}
     * @memberof ProductResponseDto
     */
    'rating'?: number;
    /**
     * Количество отзывов
     * @type {number}
     * @memberof ProductResponseDto
     */
    'reviewsCount'?: number;
    /**
     * Дата создания
     * @type {string}
     * @memberof ProductResponseDto
     */
    'createdAt': string;
    /**
     * Дата обновления
     * @type {string}
     * @memberof ProductResponseDto
     */
    'updatedAt': string;
}

