/* tslint:disable */
/* eslint-disable */
/**
 * POIZON Market API
 * API документация для маркетплейса POIZON
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProductVariantDto
 */
export interface ProductVariantDto {
    /**
     * Размер товара
     * @type {string}
     * @memberof ProductVariantDto
     */
    'size': string;
    /**
     * Цвет товара
     * @type {string}
     * @memberof ProductVariantDto
     */
    'color': string;
    /**
     * Артикул товара
     * @type {string}
     * @memberof ProductVariantDto
     */
    'sku'?: string;
    /**
     * URL изображений варианта товара
     * @type {Array<string>}
     * @memberof ProductVariantDto
     */
    'imageUrls': Array<string>;
    /**
     * Цена в юанях
     * @type {number}
     * @memberof ProductVariantDto
     */
    'priceCny': number;
    /**
     * Цена в рублях
     * @type {number}
     * @memberof ProductVariantDto
     */
    'priceRub'?: number;
    /**
     * Статус наличия товара
     * @type {string}
     * @memberof ProductVariantDto
     */
    'stockStatus': ProductVariantDtoStockStatusEnum;
}

export const ProductVariantDtoStockStatusEnum = {
    InStock: 'IN_STOCK',
    OutOfStock: 'OUT_OF_STOCK',
    LowStock: 'LOW_STOCK'
} as const;

export type ProductVariantDtoStockStatusEnum = typeof ProductVariantDtoStockStatusEnum[keyof typeof ProductVariantDtoStockStatusEnum];


