/* tslint:disable */
/* eslint-disable */
/**
 * POIZON Market API
 * API документация для маркетплейса POIZON
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProductVariantDto } from './product-variant-dto';

/**
 * 
 * @export
 * @interface ProductResponseDto
 */
export interface ProductResponseDto {
    /**
     * Название товара
     * @type {string}
     * @memberof ProductResponseDto
     */
    'name': string;
    /**
     * ID бренда товара
     * @type {string}
     * @memberof ProductResponseDto
     */
    'brand': string;
    /**
     * ID категории товара
     * @type {string}
     * @memberof ProductResponseDto
     */
    'category': string;
    /**
     * Описание товара
     * @type {string}
     * @memberof ProductResponseDto
     */
    'description'?: string;
    /**
     * Медиафайлы товара (изображения, видео)
     * @type {object}
     * @memberof ProductResponseDto
     */
    'media': object;
    /**
     * Уникальный идентификатор товара
     * @type {string}
     * @memberof ProductResponseDto
     */
    'id': string;
    /**
     * Дата создания товара
     * @type {string}
     * @memberof ProductResponseDto
     */
    'createdAt': string;
    /**
     * Дата последнего обновления товара
     * @type {string}
     * @memberof ProductResponseDto
     */
    'updatedAt': string;
    /**
     * Варианты товара
     * @type {Array<ProductVariantDto>}
     * @memberof ProductResponseDto
     */
    'variants': Array<ProductVariantDto>;
}

