/* tslint:disable */
/* eslint-disable */
/**
 * POIZON Market API
 * API документация для маркетплейса POIZON
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BrandDto } from './brand-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { CategoryDto } from './category-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { ProductVariantDto } from './product-variant-dto';

/**
 * 
 * @export
 * @interface ProductResponseDto
 */
export interface ProductResponseDto {
    /**
     * 
     * @type {string}
     * @memberof ProductResponseDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseDto
     */
    'name': string;
    /**
     * 
     * @type {object}
     * @memberof ProductResponseDto
     */
    'media': object;
    /**
     * 
     * @type {CategoryDto}
     * @memberof ProductResponseDto
     */
    'category': CategoryDto;
    /**
     * 
     * @type {BrandDto}
     * @memberof ProductResponseDto
     */
    'brand': BrandDto;
    /**
     * 
     * @type {Array<ProductVariantDto>}
     * @memberof ProductResponseDto
     */
    'variants': Array<ProductVariantDto>;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseDto
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseDto
     */
    'updatedAt': string;
}

