/* tslint:disable */
/* eslint-disable */
/**
 * POIZON Market API
 * API документация для маркетплейса POIZON
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReviewUserDto
 */
export interface ReviewUserDto {
    /**
     * ID пользователя
     * @type {string}
     * @memberof ReviewUserDto
     */
    'id': string;
    /**
     * Имя пользователя
     * @type {string}
     * @memberof ReviewUserDto
     */
    'username': string;
    /**
     * URL аватара
     * @type {string}
     * @memberof ReviewUserDto
     */
    'avatarUrl'?: string;
}

