/* tslint:disable */
/* eslint-disable */
/**
 * POIZON Market API
 * API документация для маркетплейса POIZON
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProductVariantDto } from './product-variant-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { ReviewUserDto } from './review-user-dto';

/**
 * 
 * @export
 * @interface ReviewDto
 */
export interface ReviewDto {
    /**
     * ID отзыва
     * @type {string}
     * @memberof ReviewDto
     */
    'id': string;
    /**
     * ID пользователя
     * @type {string}
     * @memberof ReviewDto
     */
    'userId': string;
    /**
     * ID варианта продукта
     * @type {string}
     * @memberof ReviewDto
     */
    'variantId': string;
    /**
     * ID продукта
     * @type {string}
     * @memberof ReviewDto
     */
    'productId': string;
    /**
     * Оценка
     * @type {number}
     * @memberof ReviewDto
     */
    'rating': number;
    /**
     * Текст отзыва
     * @type {string}
     * @memberof ReviewDto
     */
    'text': string;
    /**
     * URL фотографий
     * @type {Array<string>}
     * @memberof ReviewDto
     */
    'photos': Array<string>;
    /**
     * Видимость отзыва
     * @type {boolean}
     * @memberof ReviewDto
     */
    'isVisible': boolean;
    /**
     * Дата создания
     * @type {string}
     * @memberof ReviewDto
     */
    'createdAt': string;
    /**
     * Дата обновления
     * @type {string}
     * @memberof ReviewDto
     */
    'updatedAt': string;
    /**
     * Информация о пользователе
     * @type {ReviewUserDto}
     * @memberof ReviewDto
     */
    'user': ReviewUserDto;
    /**
     * Информация о варианте продукта
     * @type {ProductVariantDto}
     * @memberof ReviewDto
     */
    'variant': ProductVariantDto;
}

