/* tslint:disable */
/* eslint-disable */
/**
 * Poizon Market Recommendation System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SearchResponse
 */
export interface SearchResponse {
    /**
     * 
     * @type {string}
     * @memberof SearchResponse
     */
    'query': string;
    /**
     * 
     * @type {Array<object>}
     * @memberof SearchResponse
     */
    'items': Array<object>;
    /**
     * 
     * @type {number}
     * @memberof SearchResponse
     */
    'total': number;
    /**
     * 
     * @type {number}
     * @memberof SearchResponse
     */
    'page': number;
    /**
     * 
     * @type {number}
     * @memberof SearchResponse
     */
    'per_page': number;
    /**
     * 
     * @type {number}
     * @memberof SearchResponse
     */
    'total_pages': number;
}

