/* tslint:disable */
/* eslint-disable */
/**
 * POIZON Market API
 * API документация для маркетплейса POIZON
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SizeAndPriceDto
 */
export interface SizeAndPriceDto {
    /**
     * Размер
     * @type {string}
     * @memberof SizeAndPriceDto
     */
    'size': string;
    /**
     * Артикул
     * @type {string}
     * @memberof SizeAndPriceDto
     */
    'sku': string;
    /**
     * Цена в CNY
     * @type {number}
     * @memberof SizeAndPriceDto
     */
    'priceCny': number;
    /**
     * Статус наличия
     * @type {string}
     * @memberof SizeAndPriceDto
     */
    'stockStatus': string;
}

