/* tslint:disable */
/* eslint-disable */
/**
 * POIZON Market API
 * API документация для маркетплейса POIZON
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { User } from './user';

/**
 * 
 * @export
 * @interface UpdateUserResponseDto
 */
export interface UpdateUserResponseDto {
    /**
     * Обновленные данные пользователя
     * @type {User}
     * @memberof UpdateUserResponseDto
     */
    user: User;
} 