/* tslint:disable */
/* eslint-disable */
/**
 * Poizon Market Recommendation System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EventType } from './event-type';

/**
 * 
 * @export
 * @interface UserInteractionResponse
 */
export interface UserInteractionResponse {
    /**
     * 
     * @type {string}
     * @memberof UserInteractionResponse
     */
    'product_id': string;
    /**
     * 
     * @type {string}
     * @memberof UserInteractionResponse
     */
    'variant_id'?: string | null;
    /**
     * 
     * @type {EventType}
     * @memberof UserInteractionResponse
     */
    'event_type': EventType;
    /**
     * 
     * @type {string}
     * @memberof UserInteractionResponse
     */
    'category_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInteractionResponse
     */
    'brand_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInteractionResponse
     */
    'session_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInteractionResponse
     */
    'device_type'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInteractionResponse
     */
    'platform'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserInteractionResponse
     */
    'rating'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UserInteractionResponse
     */
    'review_text'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserInteractionResponse
     */
    'interaction_duration'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UserInteractionResponse
     */
    'interaction_source'?: string | null;
    /**
     * 
     * @type {object}
     * @memberof UserInteractionResponse
     */
    'interaction_metadata'?: object | null;
    /**
     * 
     * @type {number}
     * @memberof UserInteractionResponse
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof UserInteractionResponse
     */
    'user_id': string;
    /**
     * 
     * @type {string}
     * @memberof UserInteractionResponse
     */
    'created_at': string;
}



