/* tslint:disable */
/* eslint-disable */
/**
 * POIZON Market API
 * API документация для маркетплейса POIZON
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserContentUserDto } from './user-content-user-dto';

/**
 * 
 * @export
 * @interface UserContentDto
 */
export interface UserContentDto {
    /**
     * ID контента
     * @type {string}
     * @memberof UserContentDto
     */
    'id': string;
    /**
     * ID пользователя
     * @type {string}
     * @memberof UserContentDto
     */
    'userId': string;
    /**
     * ID продукта
     * @type {string}
     * @memberof UserContentDto
     */
    'productId': string;
    /**
     * Тип контента
     * @type {string}
     * @memberof UserContentDto
     */
    'type': UserContentDtoTypeEnum;
    /**
     * URL контента
     * @type {string}
     * @memberof UserContentDto
     */
    'url': string;
    /**
     * Подпись к контенту
     * @type {string}
     * @memberof UserContentDto
     */
    'caption'?: string;
    /**
     * Количество лайков
     * @type {number}
     * @memberof UserContentDto
     */
    'likesCount': number;
    /**
     * Дата создания
     * @type {string}
     * @memberof UserContentDto
     */
    'createdAt': string;
    /**
     * Дата обновления
     * @type {string}
     * @memberof UserContentDto
     */
    'updatedAt': string;
    /**
     * Информация о пользователе
     * @type {UserContentUserDto}
     * @memberof UserContentDto
     */
    'user': UserContentUserDto;
}

export const UserContentDtoTypeEnum = {
    Video: 'VIDEO',
    Photo: 'PHOTO',
    Link: 'LINK'
} as const;

export type UserContentDtoTypeEnum = typeof UserContentDtoTypeEnum[keyof typeof UserContentDtoTypeEnum];


