/* tslint:disable */
/* eslint-disable */
/**
 * Poizon Market Recommendation System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EventType } from './event-type';

/**
 * 
 * @export
 * @interface UserEventResponse
 */
export interface UserEventResponse {
    /**
     * 
     * @type {EventType}
     * @memberof UserEventResponse
     */
    'event_type': EventType;
    /**
     * 
     * @type {string}
     * @memberof UserEventResponse
     */
    'product_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserEventResponse
     */
    'session_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserEventResponse
     */
    'device_type'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserEventResponse
     */
    'platform'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserEventResponse
     */
    'duration'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UserEventResponse
     */
    'source'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserEventResponse
     */
    'referrer'?: string | null;
    /**
     * 
     * @type {object}
     * @memberof UserEventResponse
     */
    'location'?: object | null;
    /**
     * 
     * @type {string}
     * @memberof UserEventResponse
     */
    'user_agent'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserEventResponse
     */
    'ip_address'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserEventResponse
     */
    'search_query'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserEventResponse
     */
    'search_results'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UserEventResponse
     */
    'selected_position'?: number | null;
    /**
     * 
     * @type {object}
     * @memberof UserEventResponse
     */
    'metadata'?: object | null;
    /**
     * 
     * @type {number}
     * @memberof UserEventResponse
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof UserEventResponse
     */
    'user_id': string;
    /**
     * 
     * @type {string}
     * @memberof UserEventResponse
     */
    'created_at': string;
}



