/* tslint:disable */
/* eslint-disable */
/**
 * POIZON Market API
 * API документация для маркетплейса POIZON
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProductDto } from './product-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { SizeAndPriceDto } from './size-and-price-dto';

/**
 * 
 * @export
 * @interface VariantDto
 */
export interface VariantDto {
    /**
     * ID варианта
     * @type {string}
     * @memberof VariantDto
     */
    'id': string;
    /**
     * ID продукта
     * @type {string}
     * @memberof VariantDto
     */
    'productId': string;
    /**
     * Цвет
     * @type {string}
     * @memberof VariantDto
     */
    'color': string;
    /**
     * URL изображений
     * @type {Array<string>}
     * @memberof VariantDto
     */
    'imageUrls': Array<string>;
    /**
     * Размеры и цены
     * @type {Array<SizeAndPriceDto>}
     * @memberof VariantDto
     */
    'sizesAndPrices': Array<SizeAndPriceDto>;
    /**
     * Дата создания
     * @type {string}
     * @memberof VariantDto
     */
    'createdAt': string;
    /**
     * Дата обновления
     * @type {string}
     * @memberof VariantDto
     */
    'updatedAt': string;
    /**
     * Продукт
     * @type {ProductDto}
     * @memberof VariantDto
     */
    'product': ProductDto;
}

