/* tslint:disable */
/* eslint-disable */
/**
 * POIZON Market API
 * API документация для маркетплейса POIZON
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProductDto } from './product-dto';

/**
 * 
 * @export
 * @interface VariantDto
 */
export interface VariantDto {
    /**
     * ID варианта
     * @type {string}
     * @memberof VariantDto
     */
    'id': string;
    /**
     * ID продукта
     * @type {string}
     * @memberof VariantDto
     */
    'productId': string;
    /**
     * Размер
     * @type {string}
     * @memberof VariantDto
     */
    'size': string;
    /**
     * Цвет
     * @type {string}
     * @memberof VariantDto
     */
    'color': string;
    /**
     * Артикул
     * @type {string}
     * @memberof VariantDto
     */
    'sku': string;
    /**
     * Цена в CNY
     * @type {number}
     * @memberof VariantDto
     */
    'priceCny': number;
    /**
     * URL изображений
     * @type {Array<string>}
     * @memberof VariantDto
     */
    'imageUrls': Array<string>;
    /**
     * Статус наличия
     * @type {string}
     * @memberof VariantDto
     */
    'stockStatus': string;
    /**
     * Дата создания
     * @type {string}
     * @memberof VariantDto
     */
    'createdAt': string;
    /**
     * Дата обновления
     * @type {string}
     * @memberof VariantDto
     */
    'updatedAt': string;
    /**
     * Продукт
     * @type {ProductDto}
     * @memberof VariantDto
     */
    'product': ProductDto;
}

