/* tslint:disable */
/* eslint-disable */
/**
 * Poizon Market Recommendation System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BatchRecommendationRequest } from '../models';
// @ts-ignore
import type { BatchRecommendationResponse } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { ProductMetricsResponse } from '../models';
// @ts-ignore
import type { ProductMetricsUpdate } from '../models';
// @ts-ignore
import type { ProductResponse } from '../models';
// @ts-ignore
import type { RecommendationResponse } from '../models';
// @ts-ignore
import type { StatusResponse } from '../models';
// @ts-ignore
import type { UserEventCreate } from '../models';
// @ts-ignore
import type { UserEventResponse } from '../models';
// @ts-ignore
import type { UserInteractionCreate } from '../models';
// @ts-ignore
import type { UserInteractionResponse } from '../models';
// @ts-ignore
import type { UserMetricsResponse } from '../models';
// @ts-ignore
import type { UserPreferencesCreate } from '../models';
// @ts-ignore
import type { UserPreferencesResponse } from '../models';
// @ts-ignore
import type { UserPreferencesUpdate } from '../models';
/**
 * RecommendationsApi - axios parameter creator
 * @export
 */
export const RecommendationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Создать взаимодействие пользователя с товаром
         * @param {UserInteractionCreate} userInteractionCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createInteraction: async (userInteractionCreate: UserInteractionCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userInteractionCreate' is not null or undefined
            assertParamExists('createInteraction', 'userInteractionCreate', userInteractionCreate)
            const localVarPath = `/api/v1/recommendations/interactions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userInteractionCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Создать событие пользователя (альтернативный)
         * @param {UserEventCreate} userEventCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUserEventAlt: async (userEventCreate: UserEventCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userEventCreate' is not null or undefined
            assertParamExists('createUserEventAlt', 'userEventCreate', userEventCreate)
            const localVarPath = `/api/v1/recommendations/events`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userEventCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Получение пакетных рекомендаций для нескольких пользователей
         * @summary Пакетные рекомендации для пользователей
         * @param {BatchRecommendationRequest} batchRecommendationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBatchRecommendations: async (batchRecommendationRequest: BatchRecommendationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'batchRecommendationRequest' is not null or undefined
            assertParamExists('getBatchRecommendations', 'batchRecommendationRequest', batchRecommendationRequest)
            const localVarPath = `/api/v1/recommendations/batch`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(batchRecommendationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Получение персонализированных рекомендаций
         * @summary Получить персональные рекомендации
         * @param {string} userId ID пользователя
         * @param {number} [limit] 
         * @param {string | null} [category] 
         * @param {string | null} [brand] 
         * @param {number | null} [minPrice] 
         * @param {number | null} [maxPrice] 
         * @param {boolean} [includeTrending] 
         * @param {number | null} [minSimilarity] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPersonalRecommendations: async (userId: string, limit?: number, category?: string | null, brand?: string | null, minPrice?: number | null, maxPrice?: number | null, includeTrending?: boolean, minSimilarity?: number | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getPersonalRecommendations', 'userId', userId)
            const localVarPath = `/api/v1/recommendations/personal/{user_id}`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (category !== undefined) {
                localVarQueryParameter['category'] = category;
            }

            if (brand !== undefined) {
                localVarQueryParameter['brand'] = brand;
            }

            if (minPrice !== undefined) {
                localVarQueryParameter['min_price'] = minPrice;
            }

            if (maxPrice !== undefined) {
                localVarQueryParameter['max_price'] = maxPrice;
            }

            if (includeTrending !== undefined) {
                localVarQueryParameter['include_trending'] = includeTrending;
            }

            if (minSimilarity !== undefined) {
                localVarQueryParameter['min_similarity'] = minSimilarity;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Получение популярных товаров
         * @summary Получить популярные товары
         * @param {number} [limit] 
         * @param {string | null} [category] 
         * @param {string | null} [brand] 
         * @param {number | null} [minPrice] 
         * @param {number | null} [maxPrice] 
         * @param {number | null} [minPopularity] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPopularRecommendations: async (limit?: number, category?: string | null, brand?: string | null, minPrice?: number | null, maxPrice?: number | null, minPopularity?: number | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/recommendations/popular`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (category !== undefined) {
                localVarQueryParameter['category'] = category;
            }

            if (brand !== undefined) {
                localVarQueryParameter['brand'] = brand;
            }

            if (minPrice !== undefined) {
                localVarQueryParameter['min_price'] = minPrice;
            }

            if (maxPrice !== undefined) {
                localVarQueryParameter['max_price'] = maxPrice;
            }

            if (minPopularity !== undefined) {
                localVarQueryParameter['min_popularity'] = minPopularity;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Получение метрик товара
         * @summary Получить метрики товара
         * @param {string} productId ID товара
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProductMetrics: async (productId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('getProductMetrics', 'productId', productId)
            const localVarPath = `/api/v1/recommendations/metrics/product/{product_id}`
                .replace(`{${"product_id"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Получение похожих товаров
         * @summary Получить похожие товары
         * @param {string} itemId ID товара
         * @param {number} [limit] 
         * @param {string | null} [similarityType] 
         * @param {number | null} [minSimilarity] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSimilarItems: async (itemId: string, limit?: number, similarityType?: string | null, minSimilarity?: number | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'itemId' is not null or undefined
            assertParamExists('getSimilarItems', 'itemId', itemId)
            const localVarPath = `/api/v1/recommendations/similar/{item_id}`
                .replace(`{${"item_id"}}`, encodeURIComponent(String(itemId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (similarityType !== undefined) {
                localVarQueryParameter['similarity_type'] = similarityType;
            }

            if (minSimilarity !== undefined) {
                localVarQueryParameter['min_similarity'] = minSimilarity;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Получение трендовых товаров
         * @summary Получить трендовые товары
         * @param {number} [limit] 
         * @param {string | null} [category] 
         * @param {string | null} [brand] 
         * @param {number | null} [minPrice] 
         * @param {number | null} [maxPrice] 
         * @param {number | null} [minTrending] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTrendingRecommendations: async (limit?: number, category?: string | null, brand?: string | null, minPrice?: number | null, maxPrice?: number | null, minTrending?: number | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/recommendations/trending`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (category !== undefined) {
                localVarQueryParameter['category'] = category;
            }

            if (brand !== undefined) {
                localVarQueryParameter['brand'] = brand;
            }

            if (minPrice !== undefined) {
                localVarQueryParameter['min_price'] = minPrice;
            }

            if (maxPrice !== undefined) {
                localVarQueryParameter['max_price'] = maxPrice;
            }

            if (minTrending !== undefined) {
                localVarQueryParameter['min_trending'] = minTrending;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Получение событий пользователя
         * @summary Получить события пользователя
         * @param {string} userId ID пользователя
         * @param {number} [limit] 
         * @param {string | null} [eventType] 
         * @param {string | null} [startDate] 
         * @param {string | null} [endDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserEvents: async (userId: string, limit?: number, eventType?: string | null, startDate?: string | null, endDate?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserEvents', 'userId', userId)
            const localVarPath = `/api/v1/recommendations/events/{user_id}`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (eventType !== undefined) {
                localVarQueryParameter['event_type'] = eventType;
            }

            if (startDate !== undefined) {
                localVarQueryParameter['start_date'] = startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['end_date'] = endDate;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Получение метрик пользователя
         * @summary Получить метрики пользователя
         * @param {string} userId ID пользователя
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserMetrics: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserMetrics', 'userId', userId)
            const localVarPath = `/api/v1/recommendations/metrics/user/{user_id}`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Получение предпочтений пользователя
         * @summary Получить предпочтения пользователя
         * @param {string} userId ID пользователя
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserPreferences: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserPreferences', 'userId', userId)
            const localVarPath = `/api/v1/recommendations/preferences/{user_id}`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Изменить предпочтения пользователя
         * @param {UserPreferencesUpdate} userPreferencesUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putUserPreferences: async (userPreferencesUpdate: UserPreferencesUpdate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userPreferencesUpdate' is not null or undefined
            assertParamExists('putUserPreferences', 'userPreferencesUpdate', userPreferencesUpdate)
            const localVarPath = `/api/v1/recommendations/preferences`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userPreferencesUpdate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Запуск очистки старых событий
         * @summary Запустить очистку старых событий
         * @param {number} [days] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        triggerCleanupEvents: async (days?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/recommendations/tasks/cleanup-events`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (days !== undefined) {
                localVarQueryParameter['days'] = days;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Запуск обновления всех рекомендаций
         * @summary Запустить обновление всех рекомендаций
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        triggerUpdateAllRecommendations: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/recommendations/tasks/update-all-recommendations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Запуск обновления популярных товаров
         * @summary Запустить обновление популярных товаров
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        triggerUpdatePopularItems: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/recommendations/tasks/update-popular`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Запуск обновления трендовых товаров
         * @summary Запустить обновление трендовых товаров
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        triggerUpdateTrendingItems: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/recommendations/tasks/update-trending`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Обновить метрики товара
         * @param {string} productId ID товара
         * @param {ProductMetricsUpdate} productMetricsUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProductMetrics: async (productId: string, productMetricsUpdate: ProductMetricsUpdate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('updateProductMetrics', 'productId', productId)
            // verify required parameter 'productMetricsUpdate' is not null or undefined
            assertParamExists('updateProductMetrics', 'productMetricsUpdate', productMetricsUpdate)
            const localVarPath = `/api/v1/recommendations/products/{product_id}/metrics`
                .replace(`{${"product_id"}}`, encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(productMetricsUpdate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Обновление предпочтений пользователя
         * @summary Обновить предпочтения пользователя
         * @param {UserPreferencesCreate} userPreferencesCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUserPreferences: async (userPreferencesCreate: UserPreferencesCreate, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userPreferencesCreate' is not null or undefined
            assertParamExists('updateUserPreferences', 'userPreferencesCreate', userPreferencesCreate)
            const localVarPath = `/api/v1/recommendations/preferences`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userPreferencesCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RecommendationsApi - functional programming interface
 * @export
 */
export const RecommendationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RecommendationsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Создать взаимодействие пользователя с товаром
         * @param {UserInteractionCreate} userInteractionCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createInteraction(userInteractionCreate: UserInteractionCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserInteractionResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createInteraction(userInteractionCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecommendationsApi.createInteraction']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Создать событие пользователя (альтернативный)
         * @param {UserEventCreate} userEventCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createUserEventAlt(userEventCreate: UserEventCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserEventResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createUserEventAlt(userEventCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecommendationsApi.createUserEventAlt']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Получение пакетных рекомендаций для нескольких пользователей
         * @summary Пакетные рекомендации для пользователей
         * @param {BatchRecommendationRequest} batchRecommendationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBatchRecommendations(batchRecommendationRequest: BatchRecommendationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BatchRecommendationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBatchRecommendations(batchRecommendationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecommendationsApi.getBatchRecommendations']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Получение персонализированных рекомендаций
         * @summary Получить персональные рекомендации
         * @param {string} userId ID пользователя
         * @param {number} [limit] 
         * @param {string | null} [category] 
         * @param {string | null} [brand] 
         * @param {number | null} [minPrice] 
         * @param {number | null} [maxPrice] 
         * @param {boolean} [includeTrending] 
         * @param {number | null} [minSimilarity] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPersonalRecommendations(userId: string, limit?: number, category?: string | null, brand?: string | null, minPrice?: number | null, maxPrice?: number | null, includeTrending?: boolean, minSimilarity?: number | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RecommendationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPersonalRecommendations(userId, limit, category, brand, minPrice, maxPrice, includeTrending, minSimilarity, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecommendationsApi.getPersonalRecommendations']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Получение популярных товаров
         * @summary Получить популярные товары
         * @param {number} [limit] 
         * @param {string | null} [category] 
         * @param {string | null} [brand] 
         * @param {number | null} [minPrice] 
         * @param {number | null} [maxPrice] 
         * @param {number | null} [minPopularity] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPopularRecommendations(limit?: number, category?: string | null, brand?: string | null, minPrice?: number | null, maxPrice?: number | null, minPopularity?: number | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ProductResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPopularRecommendations(limit, category, brand, minPrice, maxPrice, minPopularity, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecommendationsApi.getPopularRecommendations']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Получение метрик товара
         * @summary Получить метрики товара
         * @param {string} productId ID товара
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProductMetrics(productId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProductMetricsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProductMetrics(productId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecommendationsApi.getProductMetrics']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Получение похожих товаров
         * @summary Получить похожие товары
         * @param {string} itemId ID товара
         * @param {number} [limit] 
         * @param {string | null} [similarityType] 
         * @param {number | null} [minSimilarity] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSimilarItems(itemId: string, limit?: number, similarityType?: string | null, minSimilarity?: number | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RecommendationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSimilarItems(itemId, limit, similarityType, minSimilarity, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecommendationsApi.getSimilarItems']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Получение трендовых товаров
         * @summary Получить трендовые товары
         * @param {number} [limit] 
         * @param {string | null} [category] 
         * @param {string | null} [brand] 
         * @param {number | null} [minPrice] 
         * @param {number | null} [maxPrice] 
         * @param {number | null} [minTrending] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTrendingRecommendations(limit?: number, category?: string | null, brand?: string | null, minPrice?: number | null, maxPrice?: number | null, minTrending?: number | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ProductResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTrendingRecommendations(limit, category, brand, minPrice, maxPrice, minTrending, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecommendationsApi.getTrendingRecommendations']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Получение событий пользователя
         * @summary Получить события пользователя
         * @param {string} userId ID пользователя
         * @param {number} [limit] 
         * @param {string | null} [eventType] 
         * @param {string | null} [startDate] 
         * @param {string | null} [endDate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserEvents(userId: string, limit?: number, eventType?: string | null, startDate?: string | null, endDate?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UserEventResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserEvents(userId, limit, eventType, startDate, endDate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecommendationsApi.getUserEvents']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Получение метрик пользователя
         * @summary Получить метрики пользователя
         * @param {string} userId ID пользователя
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserMetrics(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserMetricsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserMetrics(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecommendationsApi.getUserMetrics']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Получение предпочтений пользователя
         * @summary Получить предпочтения пользователя
         * @param {string} userId ID пользователя
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserPreferences(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserPreferencesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserPreferences(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecommendationsApi.getUserPreferences']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Изменить предпочтения пользователя
         * @param {UserPreferencesUpdate} userPreferencesUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putUserPreferences(userPreferencesUpdate: UserPreferencesUpdate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserPreferencesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.putUserPreferences(userPreferencesUpdate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecommendationsApi.putUserPreferences']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Запуск очистки старых событий
         * @summary Запустить очистку старых событий
         * @param {number} [days] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async triggerCleanupEvents(days?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.triggerCleanupEvents(days, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecommendationsApi.triggerCleanupEvents']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Запуск обновления всех рекомендаций
         * @summary Запустить обновление всех рекомендаций
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async triggerUpdateAllRecommendations(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.triggerUpdateAllRecommendations(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecommendationsApi.triggerUpdateAllRecommendations']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Запуск обновления популярных товаров
         * @summary Запустить обновление популярных товаров
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async triggerUpdatePopularItems(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.triggerUpdatePopularItems(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecommendationsApi.triggerUpdatePopularItems']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Запуск обновления трендовых товаров
         * @summary Запустить обновление трендовых товаров
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async triggerUpdateTrendingItems(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.triggerUpdateTrendingItems(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecommendationsApi.triggerUpdateTrendingItems']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Обновить метрики товара
         * @param {string} productId ID товара
         * @param {ProductMetricsUpdate} productMetricsUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateProductMetrics(productId: string, productMetricsUpdate: ProductMetricsUpdate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProductMetricsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateProductMetrics(productId, productMetricsUpdate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecommendationsApi.updateProductMetrics']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Обновление предпочтений пользователя
         * @summary Обновить предпочтения пользователя
         * @param {UserPreferencesCreate} userPreferencesCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateUserPreferences(userPreferencesCreate: UserPreferencesCreate, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserPreferencesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateUserPreferences(userPreferencesCreate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecommendationsApi.updateUserPreferences']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RecommendationsApi - factory interface
 * @export
 */
export const RecommendationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RecommendationsApiFp(configuration)
    return {
        /**
         * 
         * @summary Создать взаимодействие пользователя с товаром
         * @param {RecommendationsApiCreateInteractionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createInteraction(requestParameters: RecommendationsApiCreateInteractionRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserInteractionResponse> {
            return localVarFp.createInteraction(requestParameters.userInteractionCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Создать событие пользователя (альтернативный)
         * @param {RecommendationsApiCreateUserEventAltRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUserEventAlt(requestParameters: RecommendationsApiCreateUserEventAltRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserEventResponse> {
            return localVarFp.createUserEventAlt(requestParameters.userEventCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * Получение пакетных рекомендаций для нескольких пользователей
         * @summary Пакетные рекомендации для пользователей
         * @param {RecommendationsApiGetBatchRecommendationsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBatchRecommendations(requestParameters: RecommendationsApiGetBatchRecommendationsRequest, options?: RawAxiosRequestConfig): AxiosPromise<BatchRecommendationResponse> {
            return localVarFp.getBatchRecommendations(requestParameters.batchRecommendationRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Получение персонализированных рекомендаций
         * @summary Получить персональные рекомендации
         * @param {RecommendationsApiGetPersonalRecommendationsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPersonalRecommendations(requestParameters: RecommendationsApiGetPersonalRecommendationsRequest, options?: RawAxiosRequestConfig): AxiosPromise<RecommendationResponse> {
            return localVarFp.getPersonalRecommendations(requestParameters.userId, requestParameters.limit, requestParameters.category, requestParameters.brand, requestParameters.minPrice, requestParameters.maxPrice, requestParameters.includeTrending, requestParameters.minSimilarity, options).then((request) => request(axios, basePath));
        },
        /**
         * Получение популярных товаров
         * @summary Получить популярные товары
         * @param {RecommendationsApiGetPopularRecommendationsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPopularRecommendations(requestParameters: RecommendationsApiGetPopularRecommendationsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<ProductResponse>> {
            return localVarFp.getPopularRecommendations(requestParameters.limit, requestParameters.category, requestParameters.brand, requestParameters.minPrice, requestParameters.maxPrice, requestParameters.minPopularity, options).then((request) => request(axios, basePath));
        },
        /**
         * Получение метрик товара
         * @summary Получить метрики товара
         * @param {RecommendationsApiGetProductMetricsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProductMetrics(requestParameters: RecommendationsApiGetProductMetricsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ProductMetricsResponse> {
            return localVarFp.getProductMetrics(requestParameters.productId, options).then((request) => request(axios, basePath));
        },
        /**
         * Получение похожих товаров
         * @summary Получить похожие товары
         * @param {RecommendationsApiGetSimilarItemsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSimilarItems(requestParameters: RecommendationsApiGetSimilarItemsRequest, options?: RawAxiosRequestConfig): AxiosPromise<RecommendationResponse> {
            return localVarFp.getSimilarItems(requestParameters.itemId, requestParameters.limit, requestParameters.similarityType, requestParameters.minSimilarity, options).then((request) => request(axios, basePath));
        },
        /**
         * Получение трендовых товаров
         * @summary Получить трендовые товары
         * @param {RecommendationsApiGetTrendingRecommendationsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTrendingRecommendations(requestParameters: RecommendationsApiGetTrendingRecommendationsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<Array<ProductResponse>> {
            return localVarFp.getTrendingRecommendations(requestParameters.limit, requestParameters.category, requestParameters.brand, requestParameters.minPrice, requestParameters.maxPrice, requestParameters.minTrending, options).then((request) => request(axios, basePath));
        },
        /**
         * Получение событий пользователя
         * @summary Получить события пользователя
         * @param {RecommendationsApiGetUserEventsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserEvents(requestParameters: RecommendationsApiGetUserEventsRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<UserEventResponse>> {
            return localVarFp.getUserEvents(requestParameters.userId, requestParameters.limit, requestParameters.eventType, requestParameters.startDate, requestParameters.endDate, options).then((request) => request(axios, basePath));
        },
        /**
         * Получение метрик пользователя
         * @summary Получить метрики пользователя
         * @param {RecommendationsApiGetUserMetricsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserMetrics(requestParameters: RecommendationsApiGetUserMetricsRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserMetricsResponse> {
            return localVarFp.getUserMetrics(requestParameters.userId, options).then((request) => request(axios, basePath));
        },
        /**
         * Получение предпочтений пользователя
         * @summary Получить предпочтения пользователя
         * @param {RecommendationsApiGetUserPreferencesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserPreferences(requestParameters: RecommendationsApiGetUserPreferencesRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserPreferencesResponse> {
            return localVarFp.getUserPreferences(requestParameters.userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Изменить предпочтения пользователя
         * @param {RecommendationsApiPutUserPreferencesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putUserPreferences(requestParameters: RecommendationsApiPutUserPreferencesRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserPreferencesResponse> {
            return localVarFp.putUserPreferences(requestParameters.userPreferencesUpdate, options).then((request) => request(axios, basePath));
        },
        /**
         * Запуск очистки старых событий
         * @summary Запустить очистку старых событий
         * @param {RecommendationsApiTriggerCleanupEventsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        triggerCleanupEvents(requestParameters: RecommendationsApiTriggerCleanupEventsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<StatusResponse> {
            return localVarFp.triggerCleanupEvents(requestParameters.days, options).then((request) => request(axios, basePath));
        },
        /**
         * Запуск обновления всех рекомендаций
         * @summary Запустить обновление всех рекомендаций
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        triggerUpdateAllRecommendations(options?: RawAxiosRequestConfig): AxiosPromise<StatusResponse> {
            return localVarFp.triggerUpdateAllRecommendations(options).then((request) => request(axios, basePath));
        },
        /**
         * Запуск обновления популярных товаров
         * @summary Запустить обновление популярных товаров
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        triggerUpdatePopularItems(options?: RawAxiosRequestConfig): AxiosPromise<StatusResponse> {
            return localVarFp.triggerUpdatePopularItems(options).then((request) => request(axios, basePath));
        },
        /**
         * Запуск обновления трендовых товаров
         * @summary Запустить обновление трендовых товаров
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        triggerUpdateTrendingItems(options?: RawAxiosRequestConfig): AxiosPromise<StatusResponse> {
            return localVarFp.triggerUpdateTrendingItems(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Обновить метрики товара
         * @param {RecommendationsApiUpdateProductMetricsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProductMetrics(requestParameters: RecommendationsApiUpdateProductMetricsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ProductMetricsResponse> {
            return localVarFp.updateProductMetrics(requestParameters.productId, requestParameters.productMetricsUpdate, options).then((request) => request(axios, basePath));
        },
        /**
         * Обновление предпочтений пользователя
         * @summary Обновить предпочтения пользователя
         * @param {RecommendationsApiUpdateUserPreferencesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUserPreferences(requestParameters: RecommendationsApiUpdateUserPreferencesRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserPreferencesResponse> {
            return localVarFp.updateUserPreferences(requestParameters.userPreferencesCreate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createInteraction operation in RecommendationsApi.
 * @export
 * @interface RecommendationsApiCreateInteractionRequest
 */
export interface RecommendationsApiCreateInteractionRequest {
    /**
     * 
     * @type {UserInteractionCreate}
     * @memberof RecommendationsApiCreateInteraction
     */
    readonly userInteractionCreate: UserInteractionCreate
}

/**
 * Request parameters for createUserEventAlt operation in RecommendationsApi.
 * @export
 * @interface RecommendationsApiCreateUserEventAltRequest
 */
export interface RecommendationsApiCreateUserEventAltRequest {
    /**
     * 
     * @type {UserEventCreate}
     * @memberof RecommendationsApiCreateUserEventAlt
     */
    readonly userEventCreate: UserEventCreate
}

/**
 * Request parameters for getBatchRecommendations operation in RecommendationsApi.
 * @export
 * @interface RecommendationsApiGetBatchRecommendationsRequest
 */
export interface RecommendationsApiGetBatchRecommendationsRequest {
    /**
     * 
     * @type {BatchRecommendationRequest}
     * @memberof RecommendationsApiGetBatchRecommendations
     */
    readonly batchRecommendationRequest: BatchRecommendationRequest
}

/**
 * Request parameters for getPersonalRecommendations operation in RecommendationsApi.
 * @export
 * @interface RecommendationsApiGetPersonalRecommendationsRequest
 */
export interface RecommendationsApiGetPersonalRecommendationsRequest {
    /**
     * ID пользователя
     * @type {string}
     * @memberof RecommendationsApiGetPersonalRecommendations
     */
    readonly userId: string

    /**
     * 
     * @type {number}
     * @memberof RecommendationsApiGetPersonalRecommendations
     */
    readonly limit?: number

    /**
     * 
     * @type {string}
     * @memberof RecommendationsApiGetPersonalRecommendations
     */
    readonly category?: string | null

    /**
     * 
     * @type {string}
     * @memberof RecommendationsApiGetPersonalRecommendations
     */
    readonly brand?: string | null

    /**
     * 
     * @type {number}
     * @memberof RecommendationsApiGetPersonalRecommendations
     */
    readonly minPrice?: number | null

    /**
     * 
     * @type {number}
     * @memberof RecommendationsApiGetPersonalRecommendations
     */
    readonly maxPrice?: number | null

    /**
     * 
     * @type {boolean}
     * @memberof RecommendationsApiGetPersonalRecommendations
     */
    readonly includeTrending?: boolean

    /**
     * 
     * @type {number}
     * @memberof RecommendationsApiGetPersonalRecommendations
     */
    readonly minSimilarity?: number | null
}

/**
 * Request parameters for getPopularRecommendations operation in RecommendationsApi.
 * @export
 * @interface RecommendationsApiGetPopularRecommendationsRequest
 */
export interface RecommendationsApiGetPopularRecommendationsRequest {
    /**
     * 
     * @type {number}
     * @memberof RecommendationsApiGetPopularRecommendations
     */
    readonly limit?: number

    /**
     * 
     * @type {string}
     * @memberof RecommendationsApiGetPopularRecommendations
     */
    readonly category?: string | null

    /**
     * 
     * @type {string}
     * @memberof RecommendationsApiGetPopularRecommendations
     */
    readonly brand?: string | null

    /**
     * 
     * @type {number}
     * @memberof RecommendationsApiGetPopularRecommendations
     */
    readonly minPrice?: number | null

    /**
     * 
     * @type {number}
     * @memberof RecommendationsApiGetPopularRecommendations
     */
    readonly maxPrice?: number | null

    /**
     * 
     * @type {number}
     * @memberof RecommendationsApiGetPopularRecommendations
     */
    readonly minPopularity?: number | null
}

/**
 * Request parameters for getProductMetrics operation in RecommendationsApi.
 * @export
 * @interface RecommendationsApiGetProductMetricsRequest
 */
export interface RecommendationsApiGetProductMetricsRequest {
    /**
     * ID товара
     * @type {string}
     * @memberof RecommendationsApiGetProductMetrics
     */
    readonly productId: string
}

/**
 * Request parameters for getSimilarItems operation in RecommendationsApi.
 * @export
 * @interface RecommendationsApiGetSimilarItemsRequest
 */
export interface RecommendationsApiGetSimilarItemsRequest {
    /**
     * ID товара
     * @type {string}
     * @memberof RecommendationsApiGetSimilarItems
     */
    readonly itemId: string

    /**
     * 
     * @type {number}
     * @memberof RecommendationsApiGetSimilarItems
     */
    readonly limit?: number

    /**
     * 
     * @type {string}
     * @memberof RecommendationsApiGetSimilarItems
     */
    readonly similarityType?: string | null

    /**
     * 
     * @type {number}
     * @memberof RecommendationsApiGetSimilarItems
     */
    readonly minSimilarity?: number | null
}

/**
 * Request parameters for getTrendingRecommendations operation in RecommendationsApi.
 * @export
 * @interface RecommendationsApiGetTrendingRecommendationsRequest
 */
export interface RecommendationsApiGetTrendingRecommendationsRequest {
    /**
     * 
     * @type {number}
     * @memberof RecommendationsApiGetTrendingRecommendations
     */
    readonly limit?: number

    /**
     * 
     * @type {string}
     * @memberof RecommendationsApiGetTrendingRecommendations
     */
    readonly category?: string | null

    /**
     * 
     * @type {string}
     * @memberof RecommendationsApiGetTrendingRecommendations
     */
    readonly brand?: string | null

    /**
     * 
     * @type {number}
     * @memberof RecommendationsApiGetTrendingRecommendations
     */
    readonly minPrice?: number | null

    /**
     * 
     * @type {number}
     * @memberof RecommendationsApiGetTrendingRecommendations
     */
    readonly maxPrice?: number | null

    /**
     * 
     * @type {number}
     * @memberof RecommendationsApiGetTrendingRecommendations
     */
    readonly minTrending?: number | null
}

/**
 * Request parameters for getUserEvents operation in RecommendationsApi.
 * @export
 * @interface RecommendationsApiGetUserEventsRequest
 */
export interface RecommendationsApiGetUserEventsRequest {
    /**
     * ID пользователя
     * @type {string}
     * @memberof RecommendationsApiGetUserEvents
     */
    readonly userId: string

    /**
     * 
     * @type {number}
     * @memberof RecommendationsApiGetUserEvents
     */
    readonly limit?: number

    /**
     * 
     * @type {string}
     * @memberof RecommendationsApiGetUserEvents
     */
    readonly eventType?: string | null

    /**
     * 
     * @type {string}
     * @memberof RecommendationsApiGetUserEvents
     */
    readonly startDate?: string | null

    /**
     * 
     * @type {string}
     * @memberof RecommendationsApiGetUserEvents
     */
    readonly endDate?: string | null
}

/**
 * Request parameters for getUserMetrics operation in RecommendationsApi.
 * @export
 * @interface RecommendationsApiGetUserMetricsRequest
 */
export interface RecommendationsApiGetUserMetricsRequest {
    /**
     * ID пользователя
     * @type {string}
     * @memberof RecommendationsApiGetUserMetrics
     */
    readonly userId: string
}

/**
 * Request parameters for getUserPreferences operation in RecommendationsApi.
 * @export
 * @interface RecommendationsApiGetUserPreferencesRequest
 */
export interface RecommendationsApiGetUserPreferencesRequest {
    /**
     * ID пользователя
     * @type {string}
     * @memberof RecommendationsApiGetUserPreferences
     */
    readonly userId: string
}

/**
 * Request parameters for putUserPreferences operation in RecommendationsApi.
 * @export
 * @interface RecommendationsApiPutUserPreferencesRequest
 */
export interface RecommendationsApiPutUserPreferencesRequest {
    /**
     * 
     * @type {UserPreferencesUpdate}
     * @memberof RecommendationsApiPutUserPreferences
     */
    readonly userPreferencesUpdate: UserPreferencesUpdate
}

/**
 * Request parameters for triggerCleanupEvents operation in RecommendationsApi.
 * @export
 * @interface RecommendationsApiTriggerCleanupEventsRequest
 */
export interface RecommendationsApiTriggerCleanupEventsRequest {
    /**
     * 
     * @type {number}
     * @memberof RecommendationsApiTriggerCleanupEvents
     */
    readonly days?: number
}

/**
 * Request parameters for updateProductMetrics operation in RecommendationsApi.
 * @export
 * @interface RecommendationsApiUpdateProductMetricsRequest
 */
export interface RecommendationsApiUpdateProductMetricsRequest {
    /**
     * ID товара
     * @type {string}
     * @memberof RecommendationsApiUpdateProductMetrics
     */
    readonly productId: string

    /**
     * 
     * @type {ProductMetricsUpdate}
     * @memberof RecommendationsApiUpdateProductMetrics
     */
    readonly productMetricsUpdate: ProductMetricsUpdate
}

/**
 * Request parameters for updateUserPreferences operation in RecommendationsApi.
 * @export
 * @interface RecommendationsApiUpdateUserPreferencesRequest
 */
export interface RecommendationsApiUpdateUserPreferencesRequest {
    /**
     * 
     * @type {UserPreferencesCreate}
     * @memberof RecommendationsApiUpdateUserPreferences
     */
    readonly userPreferencesCreate: UserPreferencesCreate
}

/**
 * RecommendationsApi - object-oriented interface
 * @export
 * @class RecommendationsApi
 * @extends {BaseAPI}
 */
export class RecommendationsApi extends BaseAPI {
    /**
     * 
     * @summary Создать взаимодействие пользователя с товаром
     * @param {RecommendationsApiCreateInteractionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecommendationsApi
     */
    public createInteraction(requestParameters: RecommendationsApiCreateInteractionRequest, options?: RawAxiosRequestConfig) {
        return RecommendationsApiFp(this.configuration).createInteraction(requestParameters.userInteractionCreate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Создать событие пользователя (альтернативный)
     * @param {RecommendationsApiCreateUserEventAltRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecommendationsApi
     */
    public createUserEventAlt(requestParameters: RecommendationsApiCreateUserEventAltRequest, options?: RawAxiosRequestConfig) {
        return RecommendationsApiFp(this.configuration).createUserEventAlt(requestParameters.userEventCreate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Получение пакетных рекомендаций для нескольких пользователей
     * @summary Пакетные рекомендации для пользователей
     * @param {RecommendationsApiGetBatchRecommendationsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecommendationsApi
     */
    public getBatchRecommendations(requestParameters: RecommendationsApiGetBatchRecommendationsRequest, options?: RawAxiosRequestConfig) {
        return RecommendationsApiFp(this.configuration).getBatchRecommendations(requestParameters.batchRecommendationRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Получение персонализированных рекомендаций
     * @summary Получить персональные рекомендации
     * @param {RecommendationsApiGetPersonalRecommendationsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecommendationsApi
     */
    public getPersonalRecommendations(requestParameters: RecommendationsApiGetPersonalRecommendationsRequest, options?: RawAxiosRequestConfig) {
        return RecommendationsApiFp(this.configuration).getPersonalRecommendations(requestParameters.userId, requestParameters.limit, requestParameters.category, requestParameters.brand, requestParameters.minPrice, requestParameters.maxPrice, requestParameters.includeTrending, requestParameters.minSimilarity, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Получение популярных товаров
     * @summary Получить популярные товары
     * @param {RecommendationsApiGetPopularRecommendationsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecommendationsApi
     */
    public getPopularRecommendations(requestParameters: RecommendationsApiGetPopularRecommendationsRequest = {}, options?: RawAxiosRequestConfig) {
        return RecommendationsApiFp(this.configuration).getPopularRecommendations(requestParameters.limit, requestParameters.category, requestParameters.brand, requestParameters.minPrice, requestParameters.maxPrice, requestParameters.minPopularity, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Получение метрик товара
     * @summary Получить метрики товара
     * @param {RecommendationsApiGetProductMetricsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecommendationsApi
     */
    public getProductMetrics(requestParameters: RecommendationsApiGetProductMetricsRequest, options?: RawAxiosRequestConfig) {
        return RecommendationsApiFp(this.configuration).getProductMetrics(requestParameters.productId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Получение похожих товаров
     * @summary Получить похожие товары
     * @param {RecommendationsApiGetSimilarItemsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecommendationsApi
     */
    public getSimilarItems(requestParameters: RecommendationsApiGetSimilarItemsRequest, options?: RawAxiosRequestConfig) {
        return RecommendationsApiFp(this.configuration).getSimilarItems(requestParameters.itemId, requestParameters.limit, requestParameters.similarityType, requestParameters.minSimilarity, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Получение трендовых товаров
     * @summary Получить трендовые товары
     * @param {RecommendationsApiGetTrendingRecommendationsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecommendationsApi
     */
    public getTrendingRecommendations(requestParameters: RecommendationsApiGetTrendingRecommendationsRequest = {}, options?: RawAxiosRequestConfig) {
        return RecommendationsApiFp(this.configuration).getTrendingRecommendations(requestParameters.limit, requestParameters.category, requestParameters.brand, requestParameters.minPrice, requestParameters.maxPrice, requestParameters.minTrending, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Получение событий пользователя
     * @summary Получить события пользователя
     * @param {RecommendationsApiGetUserEventsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecommendationsApi
     */
    public getUserEvents(requestParameters: RecommendationsApiGetUserEventsRequest, options?: RawAxiosRequestConfig) {
        return RecommendationsApiFp(this.configuration).getUserEvents(requestParameters.userId, requestParameters.limit, requestParameters.eventType, requestParameters.startDate, requestParameters.endDate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Получение метрик пользователя
     * @summary Получить метрики пользователя
     * @param {RecommendationsApiGetUserMetricsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecommendationsApi
     */
    public getUserMetrics(requestParameters: RecommendationsApiGetUserMetricsRequest, options?: RawAxiosRequestConfig) {
        return RecommendationsApiFp(this.configuration).getUserMetrics(requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Получение предпочтений пользователя
     * @summary Получить предпочтения пользователя
     * @param {RecommendationsApiGetUserPreferencesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecommendationsApi
     */
    public getUserPreferences(requestParameters: RecommendationsApiGetUserPreferencesRequest, options?: RawAxiosRequestConfig) {
        return RecommendationsApiFp(this.configuration).getUserPreferences(requestParameters.userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Изменить предпочтения пользователя
     * @param {RecommendationsApiPutUserPreferencesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecommendationsApi
     */
    public putUserPreferences(requestParameters: RecommendationsApiPutUserPreferencesRequest, options?: RawAxiosRequestConfig) {
        return RecommendationsApiFp(this.configuration).putUserPreferences(requestParameters.userPreferencesUpdate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Запуск очистки старых событий
     * @summary Запустить очистку старых событий
     * @param {RecommendationsApiTriggerCleanupEventsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecommendationsApi
     */
    public triggerCleanupEvents(requestParameters: RecommendationsApiTriggerCleanupEventsRequest = {}, options?: RawAxiosRequestConfig) {
        return RecommendationsApiFp(this.configuration).triggerCleanupEvents(requestParameters.days, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Запуск обновления всех рекомендаций
     * @summary Запустить обновление всех рекомендаций
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecommendationsApi
     */
    public triggerUpdateAllRecommendations(options?: RawAxiosRequestConfig) {
        return RecommendationsApiFp(this.configuration).triggerUpdateAllRecommendations(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Запуск обновления популярных товаров
     * @summary Запустить обновление популярных товаров
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecommendationsApi
     */
    public triggerUpdatePopularItems(options?: RawAxiosRequestConfig) {
        return RecommendationsApiFp(this.configuration).triggerUpdatePopularItems(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Запуск обновления трендовых товаров
     * @summary Запустить обновление трендовых товаров
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecommendationsApi
     */
    public triggerUpdateTrendingItems(options?: RawAxiosRequestConfig) {
        return RecommendationsApiFp(this.configuration).triggerUpdateTrendingItems(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Обновить метрики товара
     * @param {RecommendationsApiUpdateProductMetricsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecommendationsApi
     */
    public updateProductMetrics(requestParameters: RecommendationsApiUpdateProductMetricsRequest, options?: RawAxiosRequestConfig) {
        return RecommendationsApiFp(this.configuration).updateProductMetrics(requestParameters.productId, requestParameters.productMetricsUpdate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Обновление предпочтений пользователя
     * @summary Обновить предпочтения пользователя
     * @param {RecommendationsApiUpdateUserPreferencesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecommendationsApi
     */
    public updateUserPreferences(requestParameters: RecommendationsApiUpdateUserPreferencesRequest, options?: RawAxiosRequestConfig) {
        return RecommendationsApiFp(this.configuration).updateUserPreferences(requestParameters.userPreferencesCreate, options).then((request) => request(this.axios, this.basePath));
    }
}

