import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['index.ts'],
  format: ['esm', 'cjs'],
  dts: true,
  outDir: 'dist',
  clean: true,
  minify: false,
  sourcemap: true,
  skipNodeModulesBundle: true,
  external: [
    'react',
    'react-dom',
    'next',
    '@radix-ui/*',
    'sonner',
    'date-fns',
    'clsx',
    'zod',
    'geist',
    'cmdk',
    'lucide-react',
    'embla-carousel-react',
    'recharts',
    'input-otp',
    'vaul',
    'class-variance-authority',
    'tailwind-merge',
    'tailwindcss-animate',
    '@hookform/resolvers',
    'react-hook-form',
    'react-day-picker',
    'react-resizable-panels',
    'next-themes',
  ],
}); 