/* tslint:disable */
/* eslint-disable */
/**
 * Poizon Market Recommendation System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const EventType = {
    View: 'view',
    Purchase: 'purchase',
    AddToCart: 'add_to_cart',
    RemoveFromCart: 'remove_from_cart',
    Favorite: 'favorite',
    Search: 'search',
    Click: 'click',
    Impression: 'impression',
    Share: 'share',
    Review: 'review',
    Rating: 'rating'
} as const;

export type EventType = typeof EventType[keyof typeof EventType];



