/* tslint:disable */
/* eslint-disable */
/**
 * Poizon Market Recommendation System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Типы рекомендаций
 * @export
 * @enum {string}
 */

export const RecommendationType = {
    Personal: 'personal',
    Popular: 'popular',
    Trending: 'trending',
    Similar: 'similar'
} as const;

export type RecommendationType = typeof RecommendationType[keyof typeof RecommendationType];



