/* tslint:disable */
/* eslint-disable */
/**
 * Poizon Market Recommendation System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RecommendationItem } from './recommendation-item';

/**
 * 
 * @export
 * @interface RecommendationResponse
 */
export interface RecommendationResponse {
    /**
     * 
     * @type {Array<RecommendationItem>}
     * @memberof RecommendationResponse
     */
    'items': Array<RecommendationItem>;
    /**
     * 
     * @type {number}
     * @memberof RecommendationResponse
     */
    'total'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof RecommendationResponse
     */
    'type'?: string | null;
}

