/* tslint:disable */
/* eslint-disable */
/**
 * Poizon Market Recommendation System
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserPreferencesCreate
 */
export interface UserPreferencesCreate {
    /**
     * 
     * @type {Array<string>}
     * @memberof UserPreferencesCreate
     */
    'favorite_categories'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserPreferencesCreate
     */
    'favorite_brands'?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof UserPreferencesCreate
     */
    'price_range'?: { [key: string]: number; };
    /**
     * 
     * @type {Array<number>}
     * @memberof UserPreferencesCreate
     */
    'feature_vector'?: Array<number> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserPreferencesCreate
     */
    'preferred_sizes'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserPreferencesCreate
     */
    'preferred_colors'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserPreferencesCreate
     */
    'preferred_materials'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserPreferencesCreate
     */
    'preferred_styles'?: Array<string> | null;
    /**
     * 
     * @type {Array<{ [key: string]: number; }>}
     * @memberof UserPreferencesCreate
     */
    'preferred_price_ranges'?: Array<{ [key: string]: number; }> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserPreferencesCreate
     */
    'excluded_categories'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserPreferencesCreate
     */
    'excluded_brands'?: Array<string> | null;
    /**
     * 
     * @type {object}
     * @memberof UserPreferencesCreate
     */
    'notification_preferences'?: object | null;
    /**
     * 
     * @type {object}
     * @memberof UserPreferencesCreate
     */
    'preferences_metadata'?: object | null;
}

